name: Calcul IFM AROME

on:
  schedule:
    # 3h30 après chaque run AROME (0, 6, 12, 18 UTC)
    - cron: '30 3,9,15,21 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  calcul-ifm:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Installation librairie système (eccodes)
        run: |
          sudo apt-get update
          sudo apt-get install -y libeccodes0 libeccodes-dev

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installation dépendances
        run: |
          pip install requests numpy pandas xarray cfgrib netCDF4 rioxarray

      - name: Lancement du Calcul IFM
        env:
          MF_CLIENT_ID: ${{ secrets.MF_CLIENT_ID }}
          MF_CLIENT_SECRET: ${{ secrets.MF_CLIENT_SECRET }}
        run: python calcul_ifm.py

      - name: Sauvegarde CSV et NetCDF (Artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: ifm-results-${{ github.run_number }}
          path: |
            ifm_*.csv
            netcdf_*.zip       
            retention-days: 30          
            overwrite: true
            
      - name: Commit du fichier NetCDF complet
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          
          # On ne veut garder que le fichier complet à la racine ou dans un dossier fixe
          # On déplace le fichier pour qu'il ait toujours le même nom (écrasement de l'ancien)
          cp export_netcdf/arome_fwi_complet.nc arome_fwi_complet.nc
          
          # On ajoute uniquement le fichier .nc fixe et le résumé
          git add arome_fwi_complet.nc results_summary.md
          
          # On commit seulement s'il y a des changements
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update IFM Data $(date +%Y-%m-%d_%H:%M)" && git push)
