name: Calcul IFM AROME

on:
  schedule:
    # 3h30 après chaque run AROME (0, 6, 12, 18 UTC)
    - cron: '30 3,9,15,21 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  calcul-ifm:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Installation librairie système (eccodes)
        run: |
          sudo apt-get update
          sudo apt-get install -y libeccodes0 libeccodes-dev

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installation dépendances
        run: |
          pip install requests numpy pandas xarray cfgrib netCDF4 rioxarray

      - name: Lancement du Calcul IFM
        env:
          MF_CLIENT_ID: ${{ secrets.MF_CLIENT_ID }}
          MF_CLIENT_SECRET: ${{ secrets.MF_CLIENT_SECRET }}
        run: python calcul_ifm.py

      - name: Sauvegarde CSV et NetCDF (Artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: ifm-results-${{ github.run_number }}
          path: |
            ifm_*.csv
            netcdf_*.zip
            export_netcdf/*.nc
          retention-days: 30
          overwrite: true

      - name: Commit et Push
        run: |
          git config --local user.name "GitHub Action"
          git add ifm_*.csv netcdf_*.zip
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update IFM $(date +%Y-%m-%d_%H:%M)" && git push)
